#################################### global configure #######################################

username: GitHubDaxueseng
baseurl: /StrayBirds
markdown: redcarpet
safe: false
pygments: true
title: 大学僧
