#################################### global configure #######################################

username: GitHubDaxueseng
baseurl: /StrayBirds
markdown: redcarpet
safe: false
highlighter: pygments
title: 大学僧
description: 人生到处知何似，应似飞鸿踏雪泥
theme:time-machine
